apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mural.fullname" . }}-config
  labels:
    {{- include "mural.labels" . | nindent 4 }}
data:
  PORT: {{ .Values.api.port | quote }}
  POSTGRES_USER: {{ .Values.postgres.user | quote }}
  POSTGRES_DB: {{ .Values.postgres.database | quote }}
  API_UPSTREAM: {{ printf "%s-api:80" (include "mural.fullname" .) | quote }}
