apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mural.fullname" . }}-migrations
  labels:
    {{- include "mural.labels" . | nindent 4 }}
data:
{{- (.Files.Glob "files/migrations/*.sql").AsConfig | nindent 2 }}
