apiVersion: v1
kind: Secret
metadata:
  name: {{ include "mural.fullname" . }}-db-credentials
  labels:
    {{- include "mural.labels" . | nindent 4 }}
type: Opaque
stringData:
  DATABASE_URL: {{ include "mural.databaseUrl" . | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgres.password | quote }}
